name: Publish
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write
  pull-requests: write
  repository-projects: write
  actions: write
  deployments: write

jobs:
    release:
        runs-on: ubuntu-latest
        environment: production
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            cache: 'yarn'
            node-version: 18
        - run: yarn install --frozen-lockfile
        - name: Creating .npmrc
          run: |
            cat << EOF > "$HOME/.npmrc"
              //npm.pkg.github.com/:_authToken=$NPM_TOKEN
            EOF
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        - name: Create release PR or publish
          id: release_step
          uses: changesets/action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          with:
            publish: yarn release
            createGithubReleases: true
    build:
      runs-on: ubuntu-latest
      needs: release
      steps:
        - run: echo Published ${{ needs.release.outputs.published }}
        - run: echo Packages ${{ needs.release.outputs.publishedPackages }}
    