name: Publish
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            cache: 'yarn'
            node-version: 18
        - run: yarn install --frozen-lockfile
        - run: yarn build
        - name: Create release PR or publish
          uses: changesets/action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          with:
            publish: yarn build
    
            